"""
Reflection & MoodSignal — the introspective layer of the knowledge graph.

    Reflection  — a short, factual "state-delta" insight generated by a periodic
                  background job that diffs the entity graph.  NOT psychological
                  trait inference — purely mechanical observations about what
                  changed ("JLPT mentions dropped to zero this week; exam is in
                  3 weeks").  Consumed by the greeting API to produce timely,
                  continuity-aware prompts.

    MoodSignal  — a per-entity valence tag extracted from conversation tone.
                  Never surfaced to the user as a claim about their emotions;
                  used only to inform the *tone* of the assistant's response
                  (e.g. be delicate when asking about a topic tagged
                  ``trending_negative``).
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, Text, Float, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


def _uuid() -> str:
    return uuid.uuid4().hex


def _now() -> datetime:
    return datetime.now(timezone.utc)


class Reflection(Base):
    """A periodic state-delta insight generated from the knowledge graph."""
    __tablename__ = "reflections"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id"), index=True, nullable=False
    )

    # The factual delta observation, e.g. "JLPT mentions stopped 10 days ago;
    # exam is in 3 weeks."
    content: Mapped[str] = mapped_column(Text, nullable=False)

    # Which sweep generated this: "daily" | "weekly" | "monthly"
    sweep_type: Mapped[str] = mapped_column(String, default="daily")

    # IDs of entities this reflection is about (for traceability).
    # Stored as a Postgres ARRAY of strings.
    supporting_entity_ids: Mapped[list[str] | None] = mapped_column(
        ARRAY(String), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)


class MoodSignal(Base):
    """A valence tag on an entity — sentiment that informs tone, never spoken."""
    __tablename__ = "mood_signals"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id"), index=True, nullable=False
    )

    # The entity this mood is about.  NULL = general session-level mood.
    entity_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("entities.id", ondelete="CASCADE"), nullable=True
    )

    # -1.0 (very negative) to +1.0 (very positive).
    valence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Human-readable label: "excited", "frustrated", "neutral", "trending_negative", etc.
    label: Mapped[str | None] = mapped_column(String, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
